name: Update README file

on:
  push:
    branches:
      - testing1

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Make script executable
      run: chmod +x update_readme.sh

    - name: Run script to update README
      run: ./update_readme.sh
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with latest results" || echo "No changes to commit"
        git push
    