name: Update README

on:
  push:
    branches:
      - main  # Set this to your default branch
      - testing

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run script to update README
      run: ./update_readme.sh

    - name: Commit and push if changes
      run: |
        chmod +x your_script.sh
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add README.md
        git commit -m "Update README with latest results" || exit 0  # Exit 0 if no changes
        git push
